# Generated by Django 4.2.5 on 2024-01-18 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_driver_is_market_listed'),
        ('market', '0002_alter_driverlisting_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.team')),
                ('driver_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.driverlisting')),
            ],
        ),
    ]
