# Generated by Django 4.2.5 on 2024-01-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_driver_is_market_listed'),
        ('market', '0004_alter_driverlisting_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='manager.team'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='driver_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='market.driverlisting'),
        ),
    ]
