# Generated by Django 4.2.5 on 2024-01-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_driverlisting_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
