# Generated by Django 4.2.5 on 2024-03-04 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_driver_is_market_listed'),
        ('market', '0007_driverlisting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlisting',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverlisting',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.team'),
            preserve_default=False,
        ),
    ]
