# Generated by Django 4.2.5 on 2024-03-04 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_driver_is_market_listed'),
        ('market', '0008_alter_driverlisting_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlisting',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.team'),
        ),
    ]
