# Generated by Django 4.2.5 on 2024-01-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
