racetracks = {
    "ES": {
        "name": "Circuito de España",
        "location": "ES",
        "lap_length_km": 4.7,
        "total_laps": 65,
        "straights": 40,
        "slow_corners": 30,
        "fast_corners": 30,
        "description": "Circuito de España boasts a captivating history that is the stuff of motorsport legends. This iconic racetrack, nestled in the heart of Catalonia, has a story as unique as its challenging twists and turns. Over the years, this circuit became synonymous with thrilling racing moments. The track's combination of high-speed straights, daring chicanes, and intricate hairpin turns tested the mettle of every driver who graced it."
    },
    "UK": {
        "name": "Northamptonshire circuit",
        "location": "UK",
        "lap_length_km": 5.9,
        "total_laps": 52,
        "straights": 35,
        "slow_corners": 30,
        "fast_corners": 35,
    },
    "IT": {
        "name": "Autodromo dell'Italia",
        "location": "IT",
        "lap_length_km": 5.8,
        "total_laps": 53,
        "straights": 70,
        "slow_corners": 10,
        "fast_corners": 20,
    },
    "MC": {
        "name": "Circuit de Monte Carlo",
        "location": "MC",
        "lap_length_km": 3.3,
        "total_laps": 79,
        "straights": 10,
        "slow_corners": 70,
        "fast_corners": 20,
    },
    "US": {
        "name": "Circuit of the United States",
        "location": "US",
        "lap_length_km": 5.5,
        "total_laps": 55,
        "straights": 30,
        "slow_corners": 30,
        "fast_corners": 40,
    },
    "AT": {
        "name": "Spielberg Rundkurs",
        "location": "AT",
        "lap_length_km": 4.3,
        "total_laps": 71,
        "straights": 35,
        "slow_corners": 35,
        "fast_corners": 30,
    },
    "DE": {
        "name": "Deutschring",
        "location": "DE",
        "lap_length_km": 5.1,
        "total_laps": 60,
        "straights": 40,
        "slow_corners": 35,
        "fast_corners": 25,
    },
    "BE": {
        "name": "Circuit de Belgique",
        "location": "BE",
        "lap_length_km": 7,
        "total_laps": 44,
        "straights": 40,
        "slow_corners": 25,
        "fast_corners": 35,
    },
    "FR": {
        "name": "Circuit de France",
        "location": "FR",
        "lap_length_km": 5.8,
        "total_laps": 53,
        "straights": 30,
        "slow_corners": 35,
        "fast_corners": 35,
    },
    "JP": {
        "name": "Fukuoka",
        "location": "JP",
        "lap_length_km": 5.8,
        "total_laps": 53,
        "straights": 20,
        "slow_corners": 40,
        "fast_corners": 40,
    },
}

