# Generated by Django 4.2.5 on 2023-10-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='logo_location',
            field=models.CharField(default='manager/flags/blank.png', max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='short_name',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
