# Generated by Django 4.2.5 on 2023-10-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_country_logo_location_country_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='manager.team'),
        ),
        migrations.AlterField(
            model_name='racemechanic',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_mechanic_team', to='manager.team'),
        ),
    ]
