# Generated by Django 4.2.5 on 2023-10-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_car_owner_alter_racemechanic_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='car',
            field=models.ManyToManyField(blank=True, related_name='team_car', to='manager.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_owner', to='manager.team'),
        ),
    ]
