# Generated by Django 4.2.5 on 2023-10-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_country_driver_race_racetrack_raceresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.country'),
        ),
    ]
