# Generated by Django 4.2.5 on 2023-10-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.team'),
        ),
    ]
