# Generated by Django 4.2.5 on 2023-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_team_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='team_drivers', to='manager.driver'),
        ),
    ]
