# Generated by Django 4.2.5 on 2023-10-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_manager_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='car',
        ),
        migrations.AddField(
            model_name='team',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_car', to='manager.car'),
        ),
    ]
