# Generated by Django 4.2.5 on 2023-10-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_team_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lead_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_designer', to='manager.leaddesigner'),
        ),
        migrations.AddField(
            model_name='team',
            name='race_mechanics',
            field=models.ManyToManyField(blank=True, related_name='team_race_mechanics', to='manager.racemechanic'),
        ),
    ]
