# Generated by Django 4.2.5 on 2023-10-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_raceresult_best_lap'),
    ]

    operations = [
        migrations.AddField(
            model_name='racetrack',
            name='lap_record',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
