# Generated by Django 4.2.5 on 2023-10-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_racetrack_lap_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='racetracks',
            field=models.ManyToManyField(blank=True, related_name='league_racetracks', to='manager.racetrack'),
        ),
    ]
