# Generated by Django 4.2.5 on 2023-10-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_remove_racetrack_lap_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(blank=True, null=True)),
                ('date_set', models.DateTimeField(auto_now_add=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laprecord_holder', to='manager.manager')),
                ('racetrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laprecord_racetrack', to='manager.racetrack')),
            ],
        ),
        migrations.AddField(
            model_name='racetrack',
            name='lap_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racetrack_laprecord', to='manager.laprecord'),
        ),
    ]
