# Generated by Django 4.2.5 on 2023-10-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_laprecord_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='racetrack',
            name='description',
            field=models.TextField(default='HI'),
        ),
        migrations.AddField(
            model_name='racetrack',
            name='image_location',
            field=models.CharField(default='manager/circuits/blank.png', max_length=50),
        ),
    ]
