# Generated by Django 4.2.5 on 2023-10-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_racetrack_description_racetrack_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racetrack',
            name='description',
            field=models.TextField(),
        ),
    ]
