# Generated by Django 4.2.5 on 2023-11-06 18:01

from django.db import migrations
from manager.models import Racetrack, Country
from races.constants import racetracks
from teams.constants import countries

def create_racetracks(apps, schema_editor):

    for code, racetrack in racetracks.items():
        location = Country.objects.get(short_name=racetrack["location"])
        r = Racetrack(
            name=racetrack["name"],
            location=location,
            image_location=racetrack["image_location"],
            description=racetrack["description"],
            lap_length_km=racetrack["lap_length_km"],
            total_laps=racetrack["total_laps"],
            straights=racetrack["straights"],
            slow_corners=racetrack["slow_corners"],
            fast_corners=racetrack["fast_corners"],
        )
        r.save()


def create_countries(apps, schema_editor):
    for code, country in countries.items():
            c = Country(
                name=country["name"],
                short_name=country["short_name"],
                logo_location=country["logo"],
            )
            c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_racetrack_description'),
    ]

    operations = [
        migrations.RunPython(create_countries, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_racetracks, reverse_code=migrations.RunPython.noop),
    ]
