# Generated by Django 4.2.5 on 2023-11-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_lap_race_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='best_lap',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
