# Generated by Django 4.2.5 on 2023-11-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_alter_raceresult_best_lap_alter_raceresult_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
