# Generated by Django 4.2.5 on 2023-12-06 18:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_lap_position'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='race',
            managers=[
                ('upcoming_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
