# Generated by Django 4.2.5 on 2023-12-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_season_points_championship_season_race_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
