# Generated by Django 4.2.5 on 2023-12-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_season_is_ongoing'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_driver_1', to='manager.driver')),
                ('driver_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_driver_2', to='manager.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_race', to='manager.race')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_team', to='manager.team')),
            ],
        ),
    ]
