# Generated by Django 4.2.5 on 2023-12-13 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_alter_race_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_season', to='manager.season'),
        ),
        migrations.AlterField(
            model_name='race',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_season', to='manager.season'),
        ),
    ]
