# Generated by Django 4.2.5 on 2024-01-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_raceorders_unique_race_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Points',
        ),
    ]
