# Generated by Django 4.2.5 on 2024-01-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_raceorders_unique_race_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_market_listed',
            field=models.BooleanField(default=False),
        ),
    ]
