# Generated by Django 4.2.5 on 2024-01-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_delete_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_championship_points', to='manager.championship')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_points', to='manager.team')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_championship_points', to='manager.championship')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_points', to='manager.driver')),
            ],
        ),
    ]
