# Generated by Django 4.2.5 on 2024-01-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_teampoints_driverpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverpoints',
            name='championship',
        ),
        migrations.RemoveField(
            model_name='teampoints',
            name='championship',
        ),
        migrations.AddField(
            model_name='driverpoints',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_race_points', to='manager.championship'),
        ),
        migrations.AddField(
            model_name='teampoints',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_race_points', to='manager.race'),
        ),
    ]
