# Generated by Django 4.2.5 on 2024-01-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_remove_driverpoints_championship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverpoints',
            name='race',
        ),
        migrations.RemoveField(
            model_name='teampoints',
            name='race',
        ),
        migrations.AddField(
            model_name='driverpoints',
            name='championship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_championship_points', to='manager.championship'),
        ),
        migrations.AddField(
            model_name='race',
            name='championship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_championship', to='manager.championship'),
        ),
        migrations.AddField(
            model_name='teampoints',
            name='championship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_championship_points', to='manager.championship'),
        ),
    ]
