# Generated by Django 4.2.5 on 2024-01-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_remove_driverpoints_race_remove_teampoints_race_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='laps',
        ),
    ]
